### ISSUE TITLE
Header Based Redirection 

### ISSUE THREAD

**Issue by gprime31** [r0075h3ll/Oralyzer#18]
when it says Header Based Redirection 
what headers is it using?

**Comment by r0075h3ll** [comment]
I've already written a blog post that answers your query : https://r0075h3ll.github.io/Open-Redirects-Everything-That-You-Should-Know/

**Comment by gprime31** [comment]
Thanks.
ok so the redirect: 
https://example.com//google.com shows up in the location header.
problem is   Location: https://site.com/example.com  <--- false positive and it won't redirect.
but gets flagged as header based redirection.

**Comment by r0075h3ll** [comment]
So the thing is that if the Location header exists in the response then it only shows what the website is redirecting to after sending the payload, nothing more.

**Comment by gprime31** [comment]
got it, thanks
and great tool :)

**Comment by r0075h3ll** [comment]
Thanks mate ✌️
