### ISSUE TITLE
NO module core.wayback

### ISSUE THREAD

**Issue by amaravindmenon** [r0075h3ll/Oralyzer#19]
Traceback (most recent call last):
  File "oralyzer.py", line 19, in <module>
    from core.wayback import getURLs
ModuleNotFoundError: No module named 'core.wayback'

**Comment by r0075h3ll** [comment]
can you reclone the repo and check if the issue is issue is fixed?!

**Comment by Fnoahjw** [comment]
Not fixed still showing after cloning the repo today again in termux

**Comment by amaravindmenon** [comment]
Yes its working for me now
